### PR TITLE
Merge release 2.11.0 into 3.0.x

### PR DESCRIPTION
**Pull request by ihor-sviziev**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description
This PR fixes conflicts that we had on https://github.com/laminas/laminas-server/pull/31

### CODE REVIEW

**Comment by Ocramius** [comment]
Hmm, 39aa12b doesn't look like a merge commit anymore :thinking:

**Comment by ihor-sviziev** [comment]
@Ocramius, there was a quite big conflict in the composer.lock file, so I had to update it.
Now it's not clear why the phpcs fails

**Comment by ihor-sviziev** [comment]
Does anyone could looks why the phpcs fails on this PR?

**Comment by Ocramius** [comment]
```

PHP Fatal error:  Cannot redeclare LaminasTest\Server\TestAsset\reflectionTestFunction() (previously declared in /github/workspace/test/TestAsset/reflectionTestFunction.php:25) in /github/workspace/test/TestAsset/reflectionTestFunction.php on line 27
```

Looks like it was included twice

 > Error: Start tag expected, '<' not found on line 2, column 1

perhaps there's a syntax error within that file? Is this reproducible locally?

**Comment by ihor-sviziev** [comment]
@Ocramius,


> ```
> 
> PHP Fatal error:  Cannot redeclare LaminasTest\Server\TestAsset\reflectionTestFunction() (previously declared in /github/workspace/test/TestAsset/reflectionTestFunction.php:25) in /github/workspace/test/TestAsset/reflectionTestFunction.php on line 27
> ```
> 
> Looks like it was included twice

yes, you're right, but I can't find it. Could you help me with it?

> 
> > Error: Start tag expected, '<' not found on line 2, column 1
> 
> perhaps there's a syntax error within that file? Is this reproducible locally?

the issue with phpcs - it returns "fatal error", as a result - 2nd command getting not the XML file and fails. This could be ignored

**Comment by Ocramius** [comment]
> Could you help me with it?

Unlikely, stuck with work for another while.

 > the issue with phpcs - it returns "fatal error", as a result - 2nd command getting not the XML file and fails. This could be ignored

Is this reproducible locally though?

**Comment by ihor-sviziev** [comment]
It's reproducing locally, but very strange thing that in past it was passing

**Comment by arueckauer** [comment]
According to the stacktrace the error is caused by `WebimpressCodingStandard\Sniffs\Formatting:46` where `class_exists` triggers autoloading and loads the asset file. However I am not yet sure which change is the root cause and what a proper solution is.

**Comment by froschdesign** [comment]
@arueckauer 
> …caused by `WebimpressCodingStandard\Sniffs\Formatting:46` where `class_exists` triggers autoloading and loads the asset file.

Does this mean that the file is loaded twice?

https://github.com/laminas/laminas-server/blob/b2b1c45d1dc4759438940d6e6f4d79861ff85a5f/composer.json#L37-L44

**Comment by arueckauer** [comment]
As I understand it, yes. However, removing the `files` from `composer.json` and dumping autoloading did not solve it.

**Comment by Xerkus** [comment]
make it dump stack trace each time the file is included to see which code paths trigger it

**Comment by Xerkus** [comment]
Looks like a bug in upstream.

The problem is caused by [StringClassReference](https://github.com/webimpress/coding-standard/blob/7724fbc3e22ffb3a5baca95050c863e950dafc38/src/WebimpressCodingStandard/Sniffs/Formatting/StringClassReferenceSniff.php#L46) check  
When checking string reference passed to `reflectFunction()`  https://github.com/laminas/laminas-server/blob/b2b1c45d1dc4759438940d6e6f4d79861ff85a5f/test/ReflectionTest.php#L56-L66

The fix here would potentially be to resolve those strings using `::class`  instead of literals. `::class` does not care if it is a class nor does it try to autoload it. It will probably cause issues with other checks, so alternative solution would be to disable `StringClassReference` check for those two lines.

**Comment by ihor-sviziev** [comment]
I fixed the test failure. Thank you @Xerkus!
@arueckauer @Ocramius could you review?

**Comment by Xerkus** [comment]
@ihor-sviziev could you rebase and may be squash to remove merge commits? generally linear history is preferred in PRs. Thank you.

**Comment by Ocramius** [comment]
@Xerkus if we rebase, merge-up may become harder

**Comment by ihor-sviziev** [comment]
Is there any reason why do you have the composer.lock file, but tests are always running on the lowest and the highest available versions?

**Comment by Ocramius** [comment]
@ihor-sviziev `composer.lock` is used for:

 * static analysis
 * running tests on the lowest PHP version
 * code style checks

See also https://github.com/laminas/technical-steering-committee/blob/e3036c91be7cb8da110cb869a1a35c945ee32409/meetings/minutes/2021-08-02-TSC-Minutes.md#locked-dependencies-for-all-supported-php-versions

**Review by Ocramius — APPROVED** [review]
:ship:

**Pull request merged**
