### PR TITLE
[v2] Support laminas-code:v4

### LINKED ISSUE #24: Release PHP 8 support
Hi, https://github.com/laminas/laminas-server/pull/23 brought support for PHP 8, but it's locked to `3.0.x` branch which I don't know how soon will be released.

I'd like to ask for an estimate **of work** remaining to have a `v3` release, or the willingness to merge a similar PR for `v2` branch.

### PR DESCRIPTION
**Pull request by Slamdunk**
Closes https://github.com/laminas/laminas-server/issues/24

### CODE REVIEW

**Comment by froschdesign** [comment]
@Slamdunk 
Unfortunately, The workflow for continuous integration is missing on this component. Can you add this?

**Comment by Slamdunk** [comment]
Done, waiting for https://github.com/laminas/laminas-server/pull/26 to be merged in order to rebase this

**Comment by Slamdunk** [comment]
Ok, everything seems right now, ping @weierophinney

**Comment by Slamdunk** [comment]
Ping also @froschdesign

**Review by froschdesign — APPROVED** [review]

**Comment by froschdesign** [comment]
@Slamdunk 
Thank you for your time and this contribution! 👍

**Pull request merged**
